name: CI/CD Workflow

on:
  push:
    branches:
      - master  # or your default branch name
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Install Amplify CLI
      run: npm install -g @aws-amplify/cli

    - name: Configure and Deploy to Amplify
      run: |
        amplify configure
          --accessKeyId ${{ secrets.AWS_ACCESS_KEY_ID }}
          --secretAccessKey ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          --region us-east-2
        amplify push
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
